var errorMessage = $"";
await _logService.AddExceptionAsync<>(errorMessage, ex);
return new Response(ex, errorMessage);


try
{
	// Do Work
    return new Response(true, "Success");
}
catch (Exception ex)
{
    var errorMessage = $"Error";
    await _logService.AddExceptionAsync<ApiController>(errorMessage, ex);
    return new Response(ex, errorMessage);
}

SaveMessage += $":{ex.Message}";

return await ErrorResponseAsync<UsersController>($"", ex);
